"""initial

Revision ID: f33649d85c41
Revises: 
Create Date: 2022-03-21 20:33:21.481108

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f33649d85c41'
down_revision = None
branch_labels = None
depends_on = None

opers = ['add', 'truediv', 'sub', 'mul', 'pow', 'floordiv',
         'and', 'xor', 'or', 'is', 'is_not', 'lshift', 'mod',
         'rshift', 'lt', 'le', 'eq', 'ne', 'gt', 'ge',
         'hypot', 'atan2', 'ldexp']


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('operator', postgresql.ENUM(*opers, name='whitelstd_operators'), autoincrement=False, nullable=True),
    sa.Column('number1', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('number2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('result', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Index('operator_index', 'operator'),
    sa.Index('result_index', 'result'),
    sa.PrimaryKeyConstraint('id', name='operations_pkey')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operations')
    # ### end Alembic commands ###
