FROM python:3

ADD requirements/requirements_flask.txt /calc
ADD server_files/__init__.py /calc
ADD server_files/flask_server.py /calc
ADD server_files/calc_processing /calc

RUN pip install -r /calc/requirements_flask.txt

WORKDIR /calc

CMD ["python", "flask_server.py"]

