FROM python:3

ADD server_files/calc_processing /testing
ADD server_files/tests/test_business_logic.py /testing
ADD requirements/requirements_unittests.txt /testing

RUN pip install -r /testing/requirements_unittests.txt

WORKDIR /testing

CMD ["pytest"]
