version: "3.9"
services:

  db:
    container_name: postgres_container
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_DB: calculations
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword)
    command: postgres -c listen_addresses="*"
    ports:
      - 5433:5432
    networks:
      - postgres

  migrations:
    container_name: making_migrations
    build: ./migr_test
    depends_on:
      - db
    networks:
      - postgres

  flask:
    container_name: flask_server
    build: ./flask
    ports:
      - 5000:5000
    depends_on:
      - migrations
    networks:
      - postgres

  socket:
    container_name: socket_server
    build: ./socket
    ports:
      - 65432:65432
    depends_on:
      - migrations
    networks:
      - postgres

  unit:
    container_name: unit_tests
    build: ./unit_testing
    depends_on:
      - migrations
    networks:
      - postgres

  integration:
    container_name: integration_tests
    build: ./integration_testing
    depends_on:
      - flask
      - socket
    networks:
      - postgres


networks:
  postgres:
    driver: bridge