"""mult_index

Revision ID: ch8e7g0v29i11
Revises:
Create Date: 2022-03-21 21:39:34.384926

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ch8e7g0v29i11'
down_revision = 'f33649d85c41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('mult_index', 'operations', ['operator', 'number1', 'number2'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('mult_index', 'operations')
    # ### end Alembic commands ###
